Repository Web3Philippines/matuto, pull requests merged in 2023-08, with the labels that each got.

#30 docs: how to the extension manually
  .github/assets/howtoinstall/brave/brave4.png
  .github/assets/howtoinstall/brave/brave5.png
  .github/assets/howtoinstall/chrome/chrome4.png
  .github/assets/howtoinstall/chrome/chrome5.png
  .github/assets/howtoinstall/edge/edge4.png
  .github/assets/howtoinstall/edge/edge6.png
  .github/assets/howtoinstall/firefox/firefox4.png
  README.md
Labels: docs

#31 tweak: refactor code to follow firefox guidelines
  src/assets/font/Futura-Bold.woff
  src/assets/font/Futura-Bold.woff2
  src/assets/font/FuturaBT-Book.woff
  src/assets/font/FuturaBT-Book.woff2
  src/assets/font/FuturaBT-Medium.woff
  src/assets/font/FuturaBT-Medium.woff2
  src/assets/icon_default.png
  src/index.html
  src/manifest.json
  src/popup.html
  src/script.js
Labels: tweak, under review

#25 🚀 RELEASE: v0.1.4
  .github/assets/chrome-webstore.png
  .github/assets/how_to_install/brave/brave4.png
  .github/assets/how_to_install/brave/brave5.png
  .github/assets/how_to_install/chrome/chrome4.png
  .github/assets/how_to_install/chrome/chrome5.png
  .github/assets/how_to_install/edge/edge4.png
  .github/assets/how_to_install/edge/edge6.png
  .github/assets/how_to_install/firefox/firefox4.png
  README.md
  package.json
  src/assets/font/Futura-Bold.woff
  src/assets/font/Futura-Bold.woff2
  src/assets/font/FuturaBT-Book.woff
  src/assets/font/FuturaBT-Book.woff2
  src/assets/font/FuturaBT-Medium.woff
  src/assets/font/FuturaBT-Medium.woff2
  src/assets/icon_default.png
  src/data.js
  src/index.html
  src/manifest.json
  src/popup.html
  src/script.js
  src/styles.css
Labels: chore, docs, maintainers only, planned, tweak, release

#33 tweak: remove parenthesis of each term
  src/data.js
Labels: tweak
