Repository Web3Philippines/matuto, pull requests merged in 2023-07, with the labels that each got.

#13 🚀 RELEASE: v0.1.2
  README.md
  package.json
  src/assets/cryptopinas.png
  src/assets/icon.png
  src/index.html
  src/manifest.json
  src/popup.html
  src/script.js
  src/styles.css
Labels: chore, tweak, release

#20 added firefox add-on link to readme and to popup.html
  README.md
  src/popup.html
Labels: docs, tweak, under review

#22 🚀 RELEASE: v1.0.3
  README.md
  package.json
  src/assets/bitskwela.png
  src/data.js
  src/index.html
  src/manifest.json
  src/popup.html
  src/styles.css
Labels: chore, maintainers only, release

#24 Added more definitions; order terms alphabetically
  src/data.js
Labels: tweak

#27 ✨ tweak: add terms and definitions
  src/data.js
Labels: tweak
